name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions

        ports:
          - 5433:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Django Testing
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_NAME: ${{ secrets.DATABASE_NAME }}
        DB_USER: ${{ secrets.DATABASE_USER }}
        DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DB_HOST: ${{ secrets.DATABASE_HOST }}
        DB_PORT: ${{ secrets.DATABASE_PORT }}
        DB_ENGINE: ${{secrets.DATABASE_ENGINE}}
      run: |
        python3 manage.py test
